-- ==========================================
-- 스마트 칭찬 노트 (Smart Praise Notes) 
-- Supabase 데이터베이스 생성 SQL 스크립트
-- ==========================================

-- 1. 학생 프로필 테이블 생성 (Profiles table for students)
-- 학생의 누적 칭찬 포인트 및 캐릭터 아바타, 펫 정보를 관리합니다.
create table public.profiles (
  id uuid references auth.users not null primary key,
  student_name text not null,
  points integer default 0,
  avatar_url text,
  mypet_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 칭찬 내역 기록 테이블 생성 (Praise notes table)
-- 개별 칭찬 코멘트와 적립/차감 포인트를 상세히 누적합니다.
create table public.praises (
  id bigint generated by default as identity primary key,
  student_id uuid references auth.users not null,
  student_name text not null,
  content text not null,
  points integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Row Level Security (RLS) 활성화
-- 보안 설정을 위해 테이블 단위의 행 수준 보안을 활성화합니다.
alter table public.profiles enable row level security;
alter table public.praises enable row level security;

-- 4. RLS 정책 설정 (Security Policies)

-- [Profiles 테이블 정책]
-- 모든 사용자(학생, 교사)가 모든 프로필을 조회 가능하도록 설정
create policy "Allow read profiles" on public.profiles 
  for select using (true);

-- 본인의 프로필만 추가 가능하도록 설정
create policy "Allow insert user profile" on public.profiles 
  for insert with check (auth.uid() = id);

-- 본인의 프로필 정보(아바타/펫/점수)만 직접 수정할 수 있도록 설정
create policy "Allow update user profile" on public.profiles 
  for update using (auth.uid() = id);


-- [Praises 테이블 정책]
-- 모든 사용자가 모든 학생의 칭찬 기록을 투명하게 조회할 수 있도록 허용
create policy "Allow read praises" on public.praises 
  for select using (true);

-- 본인의 칭찬 기록만 작성할 수 있도록 제한
create policy "Allow insert user praises" on public.praises 
  for insert with check (auth.uid() = student_id);
